title: 29Stratford
views:
  - path: default_view
    title: Home
    cards:
      - type: gauge
        entity: sensor.solar_production
        max: 3000
        severity:
          green: 3
          yellow: 2
          red: 1
      - type: gauge
        entity: sensor.solar_imported_power_w
        severity:
          green: 1
          yellow: 2
          red: 3
        name: Grid Import
        max: 10000
      - type: gauge
        entity: sensor.solar_exported_power_w
        max: 3000
        name: Solar - not consumed
      - type: gauge
        entity: sensor.smappee_usage_abs
        max: 10000
        name: House Consumption (ABS)
        severity:
          green: 1
          yellow: 500
          red: 1000
      - type: gauge
        entity: sensor.solar_house_consumption
        severity:
          green: 1
          yellow: 500
          red: 1000
        name: House Consumption
        max: 10000
