#####
# Notification when someone is close to home
#
#####

alias: Arriving home
id: 9009b11d-5c31-4602-92e9-859f546e5566

description: "Notify is anyone is getting close to home"

trigger:
  - platform: numeric_state
    entity_id:
      - proximity.home
    below: "300"

condition:
  condition: template
  value_template: '{{ states.proximity.home.attributes.dir_of_travel == "towards" }}'

action:
  - service: script.notify_me
    data:
      message: "🏠 Arriving home - Looks like '{{ states.proximity.home.attributes.nearest }}' is arriving home"
mode: single
