input_select:
  dishwasher_state:
    name: Dishwasher State
    initial: "Idle"
    options:
      - Idle
      - Done
      - "Off"
      - Washing

automation:
  - alias: Dishwasher Notifier
    description: >-
      Select input option dishwasher 
      based on current power use
    mode: single
    id: 0a61fd0c-5cee-406e-8eda-1b8bd4541a28
    trigger:
      - platform: state
        entity_id: sensor.gosundplug06_power
    condition: []
    action:
      - choose:
          # Machine turned off
          - conditions:
              - condition: and
                conditions:
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: input_select.dishwasher_state
                        state: "Idle"
                      - condition: state
                        entity_id: input_select.dishwasher_state
                        state: "Done"
                  - condition: numeric_state
                    entity_id: sensor.gosundplug06_power
                    below: 1
            sequence:
              - service: input_select.select_option
                data:
                  option: "Off"
                entity_id: input_select.dishwasher_state

          # Machine Turned on
          - conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_select.dishwasher_state
                    state: "Off"
                  - condition: numeric_state
                    entity_id: sensor.gosundplug06_power
                    above: 1
            sequence:
              - service: input_select.select_option
                data:
                  option: "Idle"
                entity_id: input_select.dishwasher_state

          # Machine Washing - above 5w for 5min
          - conditions:
              - condition: and
                conditions:
                  - condition: numeric_state
                    entity_id: sensor.gosundplug06_power
                    above: 5
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: input_select.dishwasher_state
                        state: "Off"
                      - condition: state
                        entity_id: input_select.dishwasher_state
                        state: "Idle"
                      - condition: state
                        entity_id: input_select.dishwasher_state
                        state: "Done"
            sequence:
              - wait_for_trigger:
                  - platform: numeric_state
                    entity_id: sensor.gosundplug06_power
                    above: 5
                    for:
                      minutes: 5
              - service: input_select.select_option
                data:
                  option: "Washing"
                entity_id: input_select.dishwasher_state

          # Machine Done - below 5w for 5min
          - conditions:
              - condition: and
                conditions:
                  - condition: numeric_state
                    entity_id: sensor.gosundplug06_power
                    below: 5
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: input_select.dishwasher_state
                        state: "Washing"
            sequence:
              - wait_for_trigger:
                  - platform: numeric_state
                    entity_id: sensor.gosundplug06_power
                    below: 5
                    for:
                      minutes: 5
                continue_on_timeout: true
                timeout: "1:01"
              - service: input_select.select_option
                data:
                  option: "Done"
                  entity_id: input_select.dishwasher_state
              - service: script.notify_me
                data:
                  message: "Good News! The dishwasher is done"

        default: []
