input_number:
  front_low_light_threshold:
    name: Front Low Light Threshold
    mode: box
    min: 0
    max: 1000
    initial: 60
    unit_of_measurement: lx
    icon: mdi:light-flood-down

sensor:
  - platform: filter
    name: LP5 5c1aad Luminance
    unique_id: lp5_5c1aad_luminance
    entity_id: sensor.esphome_web_5c1aad_illuminance
    filters:
      - filter: lowpass
        time_constant: 5
        precision: 0

template:
  - binary_sensor:
      - name: "Front Low Light"
        unique_id: front_low_light
        # 9999 - default implies NOT low light if the state is "unknown"
        state: "{{ (states('sensor.lp5_5c1aad_luminance')|float(9999)) < (states('input_number.front_low_light_threshold') | float(100)) }}"
