# @2022-06-27
# apple:ipad11-6 - (dist: 1.61) Claire's ipad
# apple:1006:10-12 - (dist: 5.4)
# apple:iphone12-1 - [MIXED] Claire / Isabelle's (dist: 1.1) iPhone 
# apple:1002:6-26 - (dist: 3)
# apple:1007:11-8 - (dist: 5.2) Simeon's iPhone 12
# apple:1005:16-5 - (dist: 4.5)
# apple:1005:10-8 - (dist: 6)
# apple:1005:9-12 - (dist: 4.82)
# apple:1005:9-26 - (dist: 5.9) Simeon's watch
sensor:
  - platform: mqtt_room
    name: "ble_sp_iphone"
    device_id: "apple:1007:11-8"
    state_topic: "espresense/devices/apple:1007:11-8"
    timeout: 60
    away_timeout: 120
  - platform: mqtt_room
    name: "ble_sp_watch"
    device_id: "apple:1005:9-26"
    state_topic: "espresense/devices/apple:1005:9-26"
    timeout: 60
    away_timeout: 120
  - platform: mqtt_room
    name: "ble_claire_iphone"
    device_id: "apple:iphone12-1"
    state_topic: "espresense/devices/apple:iphone12-1"
    timeout: 60
    away_timeout: 120
  - platform: mqtt_room
    name: "ble_apple:1006:10-12"
    device_id: "apple:1006:10-12"
    state_topic: "espresense/devices/apple:1006:10-12"
    timeout: 60
    away_timeout: 120
  - platform: mqtt_room
    name: "ble_apple:1002:6-26"
    device_id: "apple:1002:6-26"
    state_topic: "espresense/devices/apple:1002:6-26"
    timeout: 60
    away_timeout: 120
