## - Reminders to take my medicine
input_boolean:
  medicine:
    name: Medicine Reminder
    initial: true
    icon: mdi:pill

automation:
  - alias: Medicine Reminder
    id: ac17f0fd-8454-4653-a5f0-b54d3f012a70
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: "/45"
      - platform: time
        at: "08:00:00"
      - platform: state
        entity_id: person.simeon
        to: "home"

    condition:
      - condition: time
        after: "08:00:00"
      - condition: state
        entity_id: person.simeon
        state: "home"
      - condition: state
        entity_id: input_boolean.medicine
        state: "off"
    action:
      - alias: "vars"
        variables:
          meds_taken: "{{ 'TAKEN_' ~ context.id }} "
          meds_defer: "{{ 'NOT_HOME_' ~ context.id }}"
      - alias: "Ask"
        service: notify.mobile_app_sp12
        data:
          message: "Meds?"
          data:
            actions:
              - action: "{{ meds_taken }}"
                title: "Tablet Taken"
                icon: "sfsymbols:bell"
              - action: "{{ meds_defer }}"
                title: "I am not Home"
                icon: "sfsymbols:bell.slash"
      - alias: "Wait for a response"
        wait_for_trigger:
          - platform: event
            event_type: mobile_app_notification_action
            event_data:
              # waiting for the specific action avoids accidentally continuing
              # for another script/automation's notification action
              action: "{{ meds_taken }}"
          - platform: event
            event_type: mobile_app_notification_action
            event_data:
              action: "{{ meds_defer }}"
      - alias: "Perform the action"
        choose:
          - conditions: "{{ wait.trigger.event.data.action == meds_taken }}"
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.medicine
          - conditions: "{{ wait.trigger.event.data.action == meds_defer }}"
            sequence:
              - service: notify.mobile_app_sp12
                data:
                  message: "Medicine Reminder: Ok. I will remind you when you get home."
              - wait_template: >-
                  {{ states('person.simeon') == 'home' }}
              - service: notify.mobile_app_sp12
                data:
                  message: "Medicine Reminder. Now that your home, please take your medicine!"
                  data:
                    actions:
                      - action: "{{ meds_taken }}"
                        title: "Tablet Taken"
                        icon: "sfsymbols:bell"
                      - action: "{{ meds_defer }}"
                        title: "I am not Home"
                        icon: "sfsymbols:bell.slash"

  ###################################
  ##  LOG Medicine
  ###################################
  - alias: "Log Medicine Activity"
    mode: single
    id: 5dca1211-be2c-4f81-ac6b-9ec784496d3e

    trigger:
      - platform: state
        entity_id: input_boolean.medicine
        from: "off"
        to: "on"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.medicine
      - service: logbook.log
        data:
          name: "Medicine Push"
          message: "Took Medicine today."
      - service: script.notify_me
        data:
          message: "Took Medicine today"
      - delay:
          minutes: 1
  - alias: "Medicine Reset on=>off"
    mode: single
    id: f937b7b6-bdd3-446f-998e-82f8874a82ea
    trigger:
      - platform: state
        entity_id: input_boolean.medicine
        from: "on"
        to: "off"
    action:
      - service: script.notify_me
        data:
          message: "Medicine Reminder Completed"
      - delay:
          minutes: 1
