input_number:
  sprinkler_maximum_temperature_measured:
    name: "Sprinkler: Maximum Temperature Measured"
    icon: mdi:thermometer
    min: 0
    max: 100
    step: 0.01
    unit_of_measurement: "C"
  sprinkler_total_rain_fallen:
    name: "Sprinkler: Total Rain Fallen"
    icon: mdi:weather-pouring
    min: 0
    max: 100
    step: 0.01
    unit_of_measurement: "mm"
  sprinkler_watering_duration:
    name: "Sprinkler: Watering Duration"
    icon: mdi:clock
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "minutes"

input_datetime:
  sprinkler_last_watering_day:
    name: "Sprinkler: Last Watering Day"
    icon: mdi:calendar
    has_date: true
    has_time: false

template:
  - sensor:
      ##### Sprinkler Total Expected Precipitation ##################################
      - name: "Sprinkler Total Expected Precipitation"
        unique_id: 7f8aca37-be26-436d-9459-d82b6f9e96b1
        icon: mdi:weather-pouring
        unit_of_measurement: mm
        state: >
          {%- set totalprecipitation = 0 | float(0) -%}
          {%- set ns = namespace() -%} 
          {%- set ns.totalprecipitation = 0 -%}
          {%- for daypart in range(0, 7) -%}
            {%- set precipitation = state_attr('weather.openweathermap', 'forecast')[daypart].precipitation -%} 
            {%- set precipitation_probability = state_attr('weather.openweathermap', 'forecast')[daypart].precipitation_probability / 100 %}
            {% if precipitation_probability > 0 -%}
              {%- set precipitation = precipitation * precipitation_probability -%}
            {%- endif -%}
            {%- set ns.totalprecipitation = ns.totalprecipitation + precipitation -%}
          {%- endfor %}
          {{ ns.totalprecipitation | float(0) | round(2) }}

      ##### Sprinkler Total Rain Fallen Plus Expected ##################################
      - name: "Sprinkler Total Rain Fallen Plus Expected"
        unique_id: b0fafacb-9eda-463d-9ac9-bafd4d0c0a26
        icon: mdi:weather-pouring
        unit_of_measurement: mm
        state: >
          {{ (states('input_number.sprinkler_total_rain_fallen') | float(0) + states('sensor.sprinkler_total_expected_precipitation') | float(0)) | round(2) }}

      ##### Sprinkler Days Since Last Watering Day ##################################
      - name: "Sprinkler Days Since Last Watering Day"
        unique_id: 89b640e1-4234-4dc8-896f-24579c130199
        icon: mdi:calendar
        state: >
          {{ ((as_timestamp(now()) - as_timestamp(states("input_datetime.sprinkler_last_watering_day"))) / 86400) | float(0) | round(2) }}

      ##### Sprinkler Current Temperature Is Higher ##################################
      - name: "Sprinkler Current Temperature Is Higher"
        unique_id: d6eba539-5ba5-49ed-bd15-27e8b0f21e3b
        icon: mdi:check
        state: >
          {%- if states('sensor.openweathermap_temperature') | float(0) > states('input_number.sprinkler_maximum_temperature_measured') | float(0) -%}
            true
          {%- else -%}
            false
          {%- endif %}

automation:
  - alias: "Sprinkler: Add Current Rain to Total Rain Fallen"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.openweathermap_rain
    condition: []
    action:
      - data_template:
          entity_id: input_number.sprinkler_total_rain_fallen
          value: >-
            {{ states("input_number.sprinkler_total_rain_fallen")|float(0) +
            states("sensor.openweathermap_rain")|float(0) }}
        service: input_number.set_value
    mode: single
  - alias: "Sprinkler: Check if Garden should be Watered"
    description: ""
    trigger:
      - platform: sun
        event: sunrise
        offset: 0
    condition: []
    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: input_number.sprinkler_maximum_temperature_measured
                above: "31"
              - condition: numeric_state
                entity_id: sensor.sprinkler_total_rain_fallen_plus_expected
                below: "20.1"
            sequence:
              - service: input_number.set_value
                data:
                  value: 90
                target:
                  entity_id: input_number.sprinkler_watering_duration
              - service: script.sprinkler_water_the_garden
                data: {}
          - conditions:
              - condition: numeric_state
                entity_id: sensor.sprinkler_days_since_last_watering_day
                above: "2"
                below: "4"
              - condition: numeric_state
                entity_id: input_number.sprinkler_maximum_temperature_measured
                above: "26"
                below: "31.1"
              - condition: numeric_state
                entity_id: sensor.sprinkler_total_rain_fallen_plus_expected
                below: "15.1"
            sequence:
              - service: input_number.set_value
                data:
                  value: 75
                target:
                  entity_id: input_number.sprinkler_watering_duration
              - service: script.sprinkler_water_the_garden
                data: {}
          - conditions:
              - condition: numeric_state
                entity_id: sensor.sprinkler_days_since_last_watering_day
                above: "3"
                below: "4"
              - condition: numeric_state
                entity_id: input_number.sprinkler_maximum_temperature_measured
                above: "21"
                below: "26.1"
              - condition: numeric_state
                entity_id: sensor.sprinkler_total_rain_fallen_plus_expected
                below: "10.1"
            sequence:
              - service: input_number.set_value
                data:
                  value: 60
                target:
                  entity_id: input_number.sprinkler_watering_duration
              - service: script.sprinkler_water_the_garden
                data: {}
          - conditions:
              - condition: numeric_state
                entity_id: sensor.sprinkler_days_since_last_watering_day
                above: "3"
                below: "4"
              - condition: numeric_state
                entity_id: input_number.sprinkler_maximum_temperature_measured
                above: "15"
                below: "21.1"
              - condition: numeric_state
                entity_id: sensor.sprinkler_total_rain_fallen_plus_expected
                below: "10.1"
            sequence:
              - service: input_number.set_value
                data:
                  value: 45
                target:
                  entity_id: input_number.sprinkler_watering_duration
              - service: script.sprinkler_water_the_garden
                data: {}
          - conditions:
              - condition: numeric_state
                entity_id: sensor.sprinkler_days_since_last_watering_day
                above: "3"
                below: "4"
            sequence:
              - service: script.sprinkler_reset_helper_values
                data: {}
        default: []
    mode: single
  - alias: "Sprinkler: Check Maximum Temperature when Temperature Changes"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.openweathermap_temperature
    condition:
      - condition: state
        entity_id: sensor.sprinkler_current_temperature_is_higher
        state: "true"
    action:
      - service: input_number.set_value
        data_template:
          value: "{{ states('sensor.openweathermap_temperature') }}"
        target:
          entity_id: input_number.sprinkler_maximum_temperature_measured
    mode: single
  # - alias: >-
  #     Sprinkler: Check if Sprinkler is still running after a reboot of Home
  #     Assistant
  #   description: ""
  #   trigger:
  #     - platform: homeassistant
  #       event: start
  #   condition: []
  #   action:
  #     - repeat:
  #         until:
  #           - condition: not
  #             conditions:
  #               - condition: state
  #                 entity_id: switch.sw_plug_2
  #                 state: unknown
  #         sequence:
  #           - delay:
  #               hours: 0
  #               minutes: 1
  #               seconds: 0
  #               milliseconds: 0
  #     - if:
  #         - condition: device
  #           type: is_on
  #           device_id: 8137a99e9f2fc80d6d0b0192ef801c0a
  #           entity_id: switch.sw_plug_2
  #           domain: switch
  #       then:
  #         - type: turn_off
  #           device_id: 8137a99e9f2fc80d6d0b0192ef801c0a
  #           entity_id: switch.sw_plug_2
  #           domain: switch
  #         - service: script.sprinkler_reset_helper_values
  #           data: {}
  #   mode: single
