#####
# Telegram Command - /claire to get GPS location
#####

alias: Telegram - GPS Notify Claire
id: 9c48281e-2372-4e68-9b12-5c3b3013ca29

trigger:
  event_data:
    command: /claire
  event_type: telegram_command
  platform: event

action:
  - data:
      message: Claire GPS Position
    service: notify.pashley_bot
  - service: script.claire_gps_notify_telegram
initial_state: true
