#####
# Telegram Command - /eleanor to get GPS location
#####

alias: Telegram - GPS Notify Eleanor
id: 68a488ff-e8f2-42c2-b74f-eed29a1d2acc

trigger:
  event_data:
    command: /eleanor
  event_type: telegram_command
  platform: event

action:
  - data:
      message: Eleanor GPS Position
    service: notify.pashley_bot
  - service: script.eleanor_gps_notify_telegram
initial_state: true
