# restart HA to keep it fresh
alias: Restart HA
trigger: 
  platform: time
  at: "04:00:00"  
condition:
  condition: time
  weekday:
  - sun
  - wed
  - fri
action:
  - service: homeassistant.restart