#####
# Sends notifications that HA has shutdown
#####

alias: Home Assistant Shutdown - Notify
id: 2a93d8c4-5ad7-4bf3-842c-2b0940efe4a2

trigger:
  event: shutdown
  platform: homeassistant

action:
  - service: script.notify_me
    data:
      message: '*HA shutdown* Home Assistant shutting down at {{ states("sensor.time") }}'
