#####
# Sends notifications that HA has shutdown
#####

alias: Home Assistant Shutdown - Notify
id: 2a93d8c4-5ad7-4bf3-842c-2b0940efe4a2

trigger:
  event: shutdown
  platform: homeassistant

action:
  - service: script.notify_engine
    data:
      who: "simeon"
      title: "*HA shutdown*"
      value1: 'Home Assistant shutting down at {{ states("sensor.time") }}'
      group: ha
      tag_id: "information"
      importance_id: default
      color: "green"
      sticky: "false"
      timeout: 150
