#####
# Sends notifications that HA nas started
#####

- alias: Home Assistant Start - Notify
  id: d2d8775b-e666-4fb4-976d-02b4d9c5a396

  trigger:
    event: start
    platform: homeassistant

  action:
    - service: script.notify_me
      data:
        message: '*HA starting* Home Assistant starting at {{ states("sensor.time") }}'

    - service: persistent_notification.create
      data:
        title: "Automation Startup"
        message: "Waiting for startup to complete."
        notification_id: startup_delay

    # wait for entities to initialize before continuing
    - wait_template: >
        {{ is_state('input_boolean.startup_pending','off')
            or (is_state('binary_sensor.wan_connected','on')
            ) }}
      timeout:
        minutes: 5

    - service: input_boolean.turn_off
      entity_id: input_boolean.startup_pending

    - service: persistent_notification.dismiss
      data:
        notification_id: startup_delay

    - service: script.notify_me
      data:
        message: '*HA startup completed* Home Assistant started at {{ states("sensor.time") }}'
