#####
# HACS Updates notification
# Sends message to mobile device and Github - Issue #16
#####

alias: HACS Updates
id: dc99162c-4e54-47e8-b8c8-3b9396d4ac36
mode: single

trigger:
  - platform: state
    entity_id: sensor.hacs

condition:
  - condition: numeric_state
    entity_id: sensor.hacs
    above: 0

action:
  - service: script.notify_me
    data:
      message: |-
        *HACS Update*
        HACS Update(s) at {{ states("sensor.time") }} {{state_attr("sensor.hacs","repositories")}}. 
        There is {{ states('sensor.hacs') }} update.
  - service: rest_command.github_issue_state
    data:
      status: "open"
      issue_number: 2
  - service: rest_command.github_issue_comment
    data:
      repo: "There are {{ states('sensor.hacs') }} updates to HACS components at {{ states('sensor.time') }}:"
      message: |-
        HACS updates available: {{ states('sensor.hacs') }}
        {% for repo in state_attr('sensor.hacs', 'repositories') %}
        {{ repo.display_name }} {{ repo['installed_version'] }} -> {{repo['available_version'] }}

        {% endfor %}
      issue_number: 2
