#####
# Automation to daily send to Telegram inforamtion about total energy usage.
#####

alias: "Daily Energy Use Message"
id: 4da1cc10-db2b-48dc-baf9-2e6fcd423731

trigger:
  platform: time
  at: "23:59:50"

action:
  - service: script.notify_me
    data:
      message: |-
        ☀️⚡️🔥 Energy Usage
        Today's energy use was:
        ⚡️ Grid imported: {{ states('sensor.grid_imported_power_daily')|round(1, 'ceil') }}kWh  (API £{{ states('sensor.electric_cost_today')|round(2, 'ceil') }})
        ☀️ Solar exported: {{ states('sensor.solar_exported_power_daily')|round(1, 'ceil') }}kWh (£{{ states('sensor.solar_exported_power_daily_compensation')|round(2, 'ceil') }})
        ☀️ Solar production: {{ states('sensor.solar_production_daily')|round(1, 'ceil') }}kWh
        🔥 Gas: API £{{ states('sensor.gas_cost_today')|round(2, 'ceil') }}"
