alias: Increment Gas by Standing
description: ""
trigger:
  - platform: time
    at: "00:01"
condition: []
action:
  - service: input_number.increment
    target:
      entity_id: input_number.gas_daily_kwh
mode: single
