#####
# Automation to daily send to Telegram inforamtion about total energy usage.
# Also, it will create at same time new entry in CSV file containing specific daily realted data
#####

alias: "Daily Energy Use Message"
id: 9debbdb4-1369-47da-9da2-318ff0c9db6e

trigger:
  platform: time
  at: "23:59:50"

action:
  - service: script.notify_engine
    data:
      who: "simeon"
      title: "*⚡ Energy Usage*"
      value1: "Today's energy use was:
        Grid imported: {{ states('sensor.grid_imported_power_daily') }} kWh  (API £ {{ states('sensor.electric_cost_today') }})
        Solar exported: {{ states('sensor.solar_exported_power_daily') }} kWh (£{{ states('sensor.solar_exported_power_daily_compensation') }})
        Solar production: {{ states('sensor.solar_production_daily') }} kWh
        Gas: API £{{ states('sensor.gas_cost_today') }}"
      target_id: !secret telegram_bot_chat_id
      group: home
      tag_id: "information"
      importance_id: default
      color: "green"
      sticky: "false"
      timeout: 300
