id: 330e_windows_left_open
alias: 330e Windows Left Open
trigger:
  platform: state
  entity_id:
    - binary_sensor.330e_xdrive_windows
    - binary_sensor.330e_xdrive_lids
  to: "on"
  for:
    minutes: 45
action:
  - service: script.notify_me
    data:
      tts: true
      message: "*Car window open* You have left the windows open on the 330e"
