id: 330e_fueled
alias: "330e Fueled"
trigger:
  platform: state
  entity_id: binary_sensor.330e_xdrive_fuel_increased
condition:
  - condition: state
    entity_id: binary_sensor.330e_xdrive_fuel_increased
    state: "on"
action:
  - service: script.notify_me
    data:
      message: "330e has been refueled, the tank has {{ states('sensor.330e_xdrive_remaining_fuel') }} litres of petrol, with a range of {{ states('sensor.330e_xdrive_remaining_range_fuel_miles') }} miles"
