id: 330e_charged_connected
alias: "330e Charged and Connected"
trigger:
  platform: time_pattern
  minutes: "/15"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.330e_charged_connected
      state: "on"
    - condition: state
      entity_id: input_boolean.text_notifications
      state: "on"
action:
  - service: script.notify_me
    data:
      message: "330e is charged, it can be disconnected"
  - delay: 7200 # seconds until next trigger, to mitigate too many messages
