id: 330e_left_unlocked
alias: 330e Left Unlocked
trigger:
  platform: state
  entity_id: binary_sensor.330e_xdrive_door_lock_state
  to: "on"
  for:
    minutes: 30
action:
  - service: script.notify_me
    data:
      message: "*Car unlocked* You have left the 330e unlocked"
