alias: Notify Thermostat State Change
id: 29f49619-a203-4c2e-a8de-8b8b985b5895
initial_state: true
trigger:
  - platform: state
    entity_id: climate.living_room
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{% if trigger.from_state.state != trigger.to_state.state %}true{% else %}false{% endif %}"
    - condition: state
      entity_id: input_boolean.text_notifications
      state: "on"
action:
  - service: script.notify_me
    data:
      message: "Nest Thermostat changed from '{{ trigger.from_state.state }}' to '{{ trigger.to_state.state }}'."
