- alias: "Nightly reset states"
  id: 1146adcf-89a8-48ae-8940-fe2cf79bd189
  mode: single
  trigger:
    platform: time
    at: "02:12:00"
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.medicine
        - input_boolean.guest_mode

    - service: homeassistant.update_entity #Look for a new Home Assistant Version
      entity_id: binary_sensor.updater
